### PR TITLE
update icons

### PR DESCRIPTION
**Pull request by PalmerAL**
see minbrowser/min#434

### CODE REVIEW

**Comment by doreminiature** [comment]
Thank you!

**Comment by doreminiature** [comment]
@PalmerAL, I will make new build tomorrow. Don't have access to mac right now.

**Comment by PalmerAL** [comment]
Also, you may want to add a border or something around the icon so it's a bit easier to see. It's kind of hard to spot in the dock:

screen shot 2017-10-17 at 9 19 01 pm

**Comment by doreminiature** [comment]
Oh, you are right! https://i.imgur.com/9UpZMs3.png

**Comment by PalmerAL** [comment]
Small thing, but it looks like there's an extra line near the bottom of the image:

screen shot 2017-10-17 at 9 34 53 pm

**Comment by doreminiature** [comment]
I'm bad. https://i.imgur.com/qq1iL32.png

**Comment by PalmerAL** [comment]
Don't worry about it! PR: #5.

**Pull request merged**
